spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/blog;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    host: 127.0.0.1
    port: 6739

feign:
  kakao:
    url: https://dapi.kakao.com
    key:
      rest: ENC(IloiX1Sc/pg74umUTYye1pt4SDJ0zHn60RhY1TXRmA5mNNl9M7Qyor7x4CQ6IrkJ7xRNPUPjfdQ=)
  naver:
    url: https://openapi.naver.com
    key:
      id: ENC(3nkJ8KmjNG4DDVIyB5GvCLhyIzFmsb+WlzzsVL6WjBw=)
      secret: ENC(i7KHjyX1R+cMigLWfkeIVBrbipqWSk56)

jasypt:
  encryptor:
    password: doblee
    bean: standardPBEStringEncryptor